CREATE DATABASE find_food;

CREATE TABLE customer(
id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
address VARCHAR(300) DEFAULT "Not provided!",
phoneNumber VARCHAR(20),
email VARCHAR(50),
password VARCHAR(20)
);

CREATE TABLE restaurent(
id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
address VARCHAR(300) NOT NULL,
phoneNumber VARCHAR(20)
);

CREATE TABLE food(
id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
price DECIMAL(7,2),
rest_id INTEGER,
type ENUM("1","0"),
quantity INTEGER,
image_url VARCHAR(300)
);

CREATE TABLE ORDER_DETAILS(
id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
customer_id INTEGER,
food_id INTEGER,
quantity INTEGER,
total DECIMAL(7, 2),
order_date DATETIME DEFAULT NOW()
);
